### ISSUE TITLE
maven repository

### ISSUE THREAD

**Issue by binkley** [hraberg/enumerable#1]
Please upload enumerable to a maven repository somewhere.  I'd love to try this out in my projects!

**Comment by hraberg** [comment]
Closed by 42217202c083d9e958bde19dceab27dda74ea06f. Fixed spelling in readme

**Comment by hraberg** [comment]
Closed this one by mistake, reopened it.

Seems to be quite a process to add it to a central repository. May look into it for a later release. Will keep this ticket open.

You can get 0.1.0 pre-built from the Downloads tab here.

**Comment by hraberg** [comment]
Hey, better late than never, right? :-)

Being worked on, expect a 0.4.0 in Maven central in a week or so!

https://oss.sonatype.org/content/repositories/snapshots/org/enumerable/enumerable-java/0.3.1-SNAPSHOT/

**Comment by binkley** [comment]
Awesome, thanks.

**Comment by hraberg** [comment]
Now in central: http://repo1.maven.org/maven2/org/enumerable/enumerable-java/0.4.0/

**Comment by binkley** [comment]
Thank you!

Cheers,
--binkley

On Mon, Nov 7, 2011 at 6:07 PM, Håkan Råberg
reply@reply.github.com
wrote:
